language: generic

os: osx
osx_image: xcode9.2

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode9.2


before_install:
  - brew install texinfo
  - brew upgrade automake gnutls

script:
  - pushd build-scripts
  - ./fetch-emacs-mac-port.sh 26.2-rc1-mac-7.5
  - ./build-emacs.sh emacs-source 26.1.92
  - cd emacs-source; ../copylib.rb; cd -
  - ./make-zipball.sh emacs-source/tmproot 26.2-rc1-mac-7.5
  # - ./fetch-emacs-mac-port.sh head
  # - ./build-emacs.sh emacs-head 26.1.92
  # - cd emacs-head; ../copylib.rb; cd -
  # - ./make-zipball.sh emacs-head/tmproot 26.1.92-mac-head-10.12
  - popd

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH"
  file: build-scripts/emacs-source/tmproot/emacs-*.zip
  skip_cleanup: true
  draft: true
