language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode9.2


before_install:
  - brew install texinfo
  - brew upgrade automake gnutls
  - pushd build-scripts; ./patch_pkgconfig.sh; popd

script:
  - pushd build-scripts
  - ./fetch-emacs-mac-port.sh 26.2-rc1-mac-7.5
  - ./build-emacs.sh emacs-source 26.1.92
  - pushd emacs-source; ../copylib.rb; popd
  - ./make-zipball.sh emacs-source/tmproot 26.2-rc1-mac-7.5
  - ls -d $PWD/emacs-source/tmproot/*.zip
  - popd

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH"
  file_glob: true
  file: build-scripts/emacs-source/tmproot/emacs-*.zip
  skip_cleanup: true
  draft: true
