language: generic

env:
  - MACPORT_VER=26.2-mac-7.6 EMACS_VER=26.2
  # - MACPORT_VER=head EMACS_VER=26.2


matrix:
  include:
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode9.2


before_install:
  - brew install texinfo
  - brew upgrade automake gnutls
  - pushd build-scripts; ./patch_pkgconfig.sh; popd

script:
  - pushd build-scripts
  - ./fetch-emacs-mac-port.sh $MACPORT_VER
  - ./build-emacs.sh emacs-source $EMACS_VER
  - pushd emacs-source; ../copylib.rb; popd
  - ./make-zipball.sh emacs-source/tmproot $MACPORT_VER
  - ls -d $PWD/emacs-source/tmproot/*.zip
  - popd

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH"
  file_glob: true
  file: build-scripts/emacs-source/tmproot/emacs-*.zip
  skip_cleanup: true
  draft: true
