language: generic
os: osx

env:
  - MACPORT_VER=27.1-mac-8.1 EMACS_VER=27.1
  # - MACPORT_VER=head EMACS_VER=26.2


jobs:
  include:
    - os: osx
      osx_image: xcode12u
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode10.1

install:
  - ./build-scripts/prepare_homebrew.sh
  - pushd build-scripts; ./patch_pkgconfig.sh; popd

script:
  - pushd build-scripts
  - ./fetch-emacs-mac-port.sh $MACPORT_VER
  - ./build-emacs.sh emacs-source $EMACS_VER
  - pushd emacs-source; ../copylib.rb; popd
  - ./make-zipball.sh emacs-source/tmproot $MACPORT_VER
  - ls -d $PWD/emacs-source/tmproot/*.zip
  - popd

deploy:
  provider: releases
  token: "$GITHUB_OAUTH"
  file_glob: true
  file: build-scripts/emacs-source/tmproot/emacs-*.zip
  draft: true
  skip_cleanup: true
